
// Configured to work with a PS3 controller
var BUTTONS = {
	X: 0,
	CIRCLE: 1,
	SQUARE: 2,
	TRIANGLE: 3,
	L1: 4,
	R1: 5,
	L2: 6,
	R2: 7,
	SELECT: 8,
	START: 9,
	L3: 10,
	R3: 11,
	DPAD_UP: 12,
	DPAD_DOWN: 13,
	DPAD_LEFT: 14,
	DPAD_RIGHT: 15
};

// Configured to work with a PS3 controller
var JOYSTICK = {
	LEFT_X: 0,
	LEFT_Y: 1,
	RIGHT_X: 2,
	RIGHT_Y: 3
};

var EVENTS = {
	BUTTON_PRESSED: 0,
	BUTTON_RELEASED: 1,
	JOYSTICK_CHANGED: 2
};

var JOYSTICK_DIFFERENTIAL_THRESHOLD = 0.01;

var INSTRUMENT_BUTTONS = [BUTTONS.X, BUTTONS.CIRCLE, BUTTONS.SQUARE, BUTTONS.TRIANGLE,
	BUTTONS.DPAD_UP, BUTTONS.DPAD_DOWN, BUTTONS.DPAD_LEFT, BUTTONS.DPAD_RIGHT];